### ISSUE TITLE
Low TPS and High Latency for TPC-C Benchmark

### ISSUE THREAD

**Issue by keykholt** [oltpbenchmark/oltpbench#108]
I've been trying to run the TPC-C benchmark on a clean oracle database installation. The benchmark results are being reported with about 30s of latency and the database begins thrashing at 150 TPS.

The server has 112 2.2 GHz Xeon CPUs, 1 TB RAM, 9 TB storage, running Red Hat 7.1. We're running TPC-C with 100 terminals and a scale factor of 20 and the benchmark is being run from a different machine.

When I ran the benchmark previously, I was seeing very low latency and about 700 TPS, but I do not know what the settings of the database at the time was. We had to remove the database and have recently reinstalled it. Are there certain database settings in oracle that we need to change for the benchmark to work such as process limit?

**Comment by Ippokratis7** [comment]
Also note that the SF is very low for such a setup.

**Comment by apavlo** [comment]
Are you really asking us how to tune Oracle for you? That's not what we are trying to do with this project. 

But with that said, @Ippokratis7 is right that you are only running with 20 warehouses (scalefactor = # of warehouses). That's why you are running so slow. Are you sure the DBMS is thrashing disk? I bet if you looked at lock contention stats you would see that's what all your txns are blocked on each other.

Try running at a lower isolation level. I bet that solves your problem. Then increase the scale factor to run your real experiments.

**Comment by keykholt** [comment]
What is fanync latency and how would I check this? I realize the scale factor is low, but I was trying to reproduce what I had before.

**Comment by apavlo** [comment]
Mark meant "fsync" not "faync".

**Comment by keykholt** [comment]
Ok I'll try that and see if it changes.
